### ISSUE TITLE
Hangs on “listening on port 3000”

### ISSUE THREAD

**Issue by Anuiran** [brandonros/nexustk#3]
Can’t get the console to respond to anything after that message is displayed to the screen.

Also do you have an email or any other way to contact you?

**Comment by nmanley** [comment]
The encryption has changed and it doesn’t work.

**Comment by brandonros** [comment]
I'll fix it.

**Comment by brandonros** [comment]
> The encryption has changed and it doesn’t work.

Any other additional info you can share that would help me out?

**Comment by nmanley** [comment]
@brandonros It looks like they are changing the packet tail every client update. That's about as far into it as I dug.

I just did a fresh branch off master and it's throwing the Version wrong error.

**Comment by brandonros** [comment]
https://github.com/brandonros/nexustk/commit/b8d587cc860fb24461f71c180290fc492788b31a

Version updated.

**Comment by brandonros** [comment]
`client.global_key = 'Urk#nI7ni';`

Do you feel this is no longer the global key?

**Comment by Anuiran** [comment]
It’s the same key, darkages uses so I’d imagine it’s still the same, but unsure.

**Comment by brandonros** [comment]
```
module.exports = function (id, inc, payload, short_arg, byte_arg) {
	var buf = Buffer.concat([new Buffer([id, inc]), new Buffer(payload)]);

	var md5_buf = utilities.md5(buf);

	var tail = new Buffer(7);

	tail[0] = md5_buf[0x0D];
	tail[1] = md5_buf[0x03];
	tail[2] = md5_buf[0x0B];
	tail[3] = md5_buf[0x07];

	tail[4] = (short_arg & 0x800000FF) ^ 0x61;
	tail[5] = (byte_arg & 0x800000FF) ^ 0x25;
	tail[6] = ((short_arg >> 8) & 0x800000FF) ^ 0x23;

	return tail;
};
```

so that would leave this function in question

Let me open the 7.50 NexusTK.exe and try to find this function again in OllyDbg

**Comment by nmanley** [comment]
I haven’t fired up IDA yet. Ill take a look if you haven’t already. I can’t see the tail changing too too much. 

I also haven’t spent enough time on it either.

**Comment by brandonros** [comment]
For what it is worth, this issue is kind of misguided.

It doesn't really "hang on listening on port 3000"

You have to hit it with your web browser to open up the socket and kick off connection initialization, after which you'll get an error.

But I'll leave it open while we fix the encryption issue (if there is one, I haven't confirmed or unconfirmed it yet)

**Comment by nmanley** [comment]
@brandonros I only suggested encryption from information provided by private server operators and the battles they’re facing.

Rotation encryption seems to be the method KRU is using to combat private servers.

**Comment by brandonros** [comment]
I didn't need to make any changes. I was able to login fine and everything seems to be working. Encryption looks unchanged to me.

@Anuiran please follow the steps in the README more closely. Running the backend/server.js is only half of the battle. You need to load the frontend too (which hits the API)

**Comment by Anuiran** [comment]
I understand all that.

The issue is I can’t do any command after after the node backend.js

I had changed version, I had changed name. I did all the config.

The console freezes and allows no input to run the other command. It just hangs on “listening on port 3000....”


![inage of console window](https://i.imgur.com/ddifNFp.png)

**Comment by brandonros** [comment]
@Anuiran You need to open a second console and run the command separately.

**Comment by nmanley** [comment]
Did you edit the frontend/config.js to include your credentials. Finally just open frontend/index.html

I generally test it with an account that's in proximity to the other.

**Comment by brandonros** [comment]
@nmanley Want to pair with me and get map detection working so we could add https://en.wikipedia.org/wiki/A*_search_algorithm to this? :) I don't wanna make a farmbot, but... maybe make a farmbot?

**Comment by nmanley** [comment]
@brandonros are you on telegram/facebook at all?

**Comment by Anuiran** [comment]
@brandonros @nmanley 

If either of you are interested in that stuff, I have a lot of map code and other stuff you might find interesting if there’s a way to contact you.

**Comment by nmanley** [comment]
@brandonros I have a group of people also interested. I'll email you my info.

**Comment by Anuiran** [comment]
@brandonros @nmanley 

![5C0E321A-624C-4D2B-A86F-134924BF0319](https://user-images.githubusercontent.com/46170781/71839362-dd44d400-306f-11ea-8ef6-c559a0e76543.jpeg)

I have very interesting things you might like if I can get someone’s contact information.

**Comment by Anuiran** [comment]
@brandonros @nmanley 

`[PacketHandler(0x15)]
    private bool ProcessSMapSizePacket(Client client, ServerPacket packet)
        {
            var mapNumber = (int)packet.ReadInt16();
            var width = packet.ReadByte();
            var height = packet.ReadByte();
            var mapAttributes = (MapAttributes)packet.ReadByte();
            var unknown = packet.ReadBytes(2);
            var crc = packet.ReadUInt16();
            var name = packet.ReadString8();

           if (client.CustomMapAttributesEnabled)
                packet.Data[4] = (byte)client.CustomMapAttributes;

            if (Maps.TryGetValue(mapNumber, out Map map))
                map.Attributes = mapAttributes;
            else
            {
                map = new Map(mapNumber, mapNumber new Size(width, height), mapAttributes, crc, name);
                Maps[mapNumber] = map;
            }

            client.Map = map;
            client.NearbyObjectIds.Clear();
            client.NearbyHumanIds.Clear();
            client.NearbyMonsterIds.Clear();
            client.NearbyMerchantIds.Clear();
            client.NearbyMerchantObjects.Clear();
            client.NearbyHumanObjects.Clear();

            var mapFileName = $@"C:\Nexon\Kingdom of Winds\maps\Ba{mapNumber}.cmp";

            client.Map.IsLoading = true;

            if (File.Exists(mapFileName))
            {
                var mapData = File.ReadAllBytes(mapFileName);
                if (CRC16.Calculate(mapData) == crc)
                {
                    map.SetData(mapData);
                    client.Map.IsLoading = false;
                }
            }
    } `
