### ISSUE TITLE
Old Issue (frontend actions do not work)

### ISSUE THREAD

**Issue by eppjeff** [brandonros/nexustk#4]
Huh, today I saw some updates to the project and guess I'll finally report this issue if it's being worked on again. Perhaps it is just my own stupidity.... but here's the problem.

I can get the character logged in, I can view the the frontend just fine. Using chrome dev tools, I can see the console logs for actions taking place. However, 

None of the buttons work. Clicking "attack" for example will just say "Emitting attack for [characterName]" but in game the attack will never happen. I'm not sure where the failure lies.

**Comment by brandonros** [comment]
KRU changed the encryption

I need to update this codebase to match their changes

I’ll follow up on this issue when I do

Regards,

Brandon

________________________________

**Comment by brandonros** [comment]
Frontend actions are fixed.

**Comment by eppjeff** [comment]
Oh wow you added a lot!
